-- MySQL Script generated by MySQL Workbench
-- Sun Feb 21 20:34:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema b1hjbod5x53zcqbm37to
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b1hjbod5x53zcqbm37to
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b1hjbod5x53zcqbm37to` DEFAULT CHARACTER SET utf8 ;
USE `b1hjbod5x53zcqbm37to` ;

-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Location` (
  `Location_ID` MEDIUMINT(9) NOT NULL,
  `Request_Active` MEDIUMINT(9) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Last_Cleaned` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Location_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Complaints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Complaints` (
  `Complaint_ID` MEDIUMINT(9) NOT NULL,
  `Category` MEDIUMINT(9) NOT NULL,
  `Rating` MEDIUMINT(9) NULL DEFAULT NULL,
  `Remarks` TEXT NULL DEFAULT NULL,
  `Start_time` DATETIME NOT NULL,
  `End_time` DATETIME NULL DEFAULT NULL,
  `Resolved` MEDIUMINT(9) NOT NULL,
  `Location_ID` MEDIUMINT(9) NOT NULL,
  `ID` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`Complaint_ID`),
  INDEX `Complaints_ibfk_1` (`Location_ID` ASC) VISIBLE,
  CONSTRAINT `Complaints_ibfk_1`
    FOREIGN KEY (`Location_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Location` (`Location_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Hostel_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Hostel_Room` (
  `Location_ID` MEDIUMINT(9) NOT NULL,
  `Request_Active` MEDIUMINT(9) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Last_Cleaned` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Location_ID`),
  CONSTRAINT `fk_location`
    FOREIGN KEY (`Location_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Location` (`Location_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Institute_Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Institute_Admins` (
  `ID` MEDIUMINT(9) NOT NULL,
  `First_name` VARCHAR(255) NOT NULL,
  `Last_name` VARCHAR(255) NOT NULL,
  `Age` MEDIUMINT(9) NOT NULL,
  `Gender` MEDIUMINT(9) NOT NULL,
  `Contact_number` VARCHAR(100) NOT NULL,
  `Designation` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Security`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Security` (
  `Security_ID` MEDIUMINT(9) NOT NULL,
  `First_name` VARCHAR(255) NOT NULL,
  `Last_name` VARCHAR(255) NOT NULL,
  `Age` MEDIUMINT(9) NOT NULL,
  `Gender` MEDIUMINT(9) NOT NULL,
  `Contact_number` VARCHAR(100) NOT NULL,
  `Temperature` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`Security_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Students` (
  `ID` MEDIUMINT(9) NOT NULL,
  `First_name` VARCHAR(255) NOT NULL,
  `Last_name` VARCHAR(255) NOT NULL,
  `Age` MEDIUMINT(9) NOT NULL,
  `Gender` MEDIUMINT(9) NOT NULL,
  `Contact_number` VARCHAR(100) NOT NULL,
  `Last_Health_Check` DATETIME NULL DEFAULT NULL,
  `Year` MEDIUMINT(9) NOT NULL,
  `Location_ID` MEDIUMINT(9) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Students_ibfk_1` (`Location_ID` ASC) VISIBLE,
  CONSTRAINT `Students_ibfk_1`
    FOREIGN KEY (`Location_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Location` (`Location_ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`Workers` (
  `ID` MEDIUMINT(9) NOT NULL,
  `First_name` VARCHAR(255) NOT NULL,
  `Last_name` VARCHAR(255) NOT NULL,
  `Age` MEDIUMINT(9) NOT NULL,
  `Gender` MEDIUMINT(9) NOT NULL,
  `Contact_number` VARCHAR(100) NOT NULL,
  `Salary` MEDIUMINT(9) NOT NULL,
  `Duty` MEDIUMINT(9) NOT NULL,
  `Temperature` MEDIUMINT(9) NOT NULL,
  `Avg_Rating` MEDIUMINT(9) NULL DEFAULT NULL,
  `Last_Assigned` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`assignments` (
  `ID` MEDIUMINT(9) NOT NULL,
  `Complaint_ID` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`Complaint_ID`),
  INDEX `fk1_assignments_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk1_assignments`
    FOREIGN KEY (`ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Workers` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`fms_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`fms_admin` (
  `ID` MEDIUMINT(9) NOT NULL,
  `last_checked` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_institute`
    FOREIGN KEY (`ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Institute_Admins` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`assigns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`assigns` (
  `Worker_ID` MEDIUMINT(9) NOT NULL,
  `FMS_ID` MEDIUMINT(9) NOT NULL,
  `Complaint_ID` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`Complaint_ID`),
  INDEX `fk1_idx` (`Worker_ID` ASC) VISIBLE,
  INDEX `fk2_idx` (`FMS_ID` ASC) VISIBLE,
  CONSTRAINT `fk1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Workers` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk2`
    FOREIGN KEY (`FMS_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`fms_admin` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk3`
    FOREIGN KEY (`Complaint_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Complaints` (`Complaint_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`checkin` (
  `Security_ID` MEDIUMINT(9) NOT NULL,
  `visitor_id` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`visitor_id`),
  INDEX `Security_ID` (`Security_ID` ASC) VISIBLE,
  CONSTRAINT `checkin_ibfk_1`
    FOREIGN KEY (`Security_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Security` (`Security_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`visitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`visitor` (
  `visitor_id` MEDIUMINT(9) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `entry_time` DATETIME NOT NULL,
  `declaration` TEXT NOT NULL,
  `exit_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`visitor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`warden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`warden` (
  `ID` MEDIUMINT(9) NOT NULL,
  `last_checked` DATETIME NOT NULL,
  `hostel_no` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_warden`
    FOREIGN KEY (`ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Institute_Admins` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1hjbod5x53zcqbm37to`.`washroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1hjbod5x53zcqbm37to`.`washroom` (
  `Location_ID` MEDIUMINT(9) NOT NULL,
  `Image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`Location_ID`),
  CONSTRAINT `fk_location1`
    FOREIGN KEY (`Location_ID`)
    REFERENCES `b1hjbod5x53zcqbm37to`.`Location` (`Location_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
